# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('username', models.CharField(max_length=32, verbose_name='Your Name or Nick')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('delete_period', models.PositiveIntegerField(choices=[(1, 'One Day'), (2, 'One Week'), (3, 'One Month'), (4, 'One Year')], verbose_name='Delete In')),
            ],
        ),
        migrations.CreateModel(
            name='Syntax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pasteitem',
            name='syntax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paste.Syntax', verbose_name='Syntax'),
        ),
    ]
