# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 17, 15, 6, 25, 72489, tzinfo=utc), verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
